/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCropAdviceRouteImport } from './routes/api/crop-advice'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCropAdviceRoute = ApiCropAdviceRouteImport.update({
  id: '/api/crop-advice',
  path: '/api/crop-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/crop-advice': typeof ApiCropAdviceRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/crop-advice': typeof ApiCropAdviceRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/crop-advice': typeof ApiCropAdviceRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/crop-advice' | '/api/translate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/crop-advice' | '/api/translate'
  id: '__root__' | '/' | '/api/crop-advice' | '/api/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCropAdviceRoute: typeof ApiCropAdviceRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crop-advice': {
      id: '/api/crop-advice'
      path: '/api/crop-advice'
      fullPath: '/api/crop-advice'
      preLoaderRoute: typeof ApiCropAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCropAdviceRoute: ApiCropAdviceRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
