/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropDoctorRouteImport } from './routes/crop-doctor'
import { Route as DiseaseScannerRouteImport } from './routes/disease-scanner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiCropAdviceRouteImport } from './routes/api/crop-advice'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropDoctorRoute = CropDoctorRouteImport.update({
  id: '/crop-doctor',
  path: '/crop-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseScannerRoute = DiseaseScannerRouteImport.update({
  id: '/disease-scanner',
  path: '/disease-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCropAdviceRoute = ApiCropAdviceRouteImport.update({
  id: '/api/crop-advice',
  path: '/api/crop-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/disease-scanner': typeof DiseaseScannerRoute
  '/profile': typeof ProfileRoute
  '/api/crop-advice': typeof ApiCropAdviceRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/disease-scanner': typeof DiseaseScannerRoute
  '/profile': typeof ProfileRoute
  '/api/crop-advice': typeof ApiCropAdviceRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/disease-scanner': typeof DiseaseScannerRoute
  '/profile': typeof ProfileRoute
  '/api/crop-advice': typeof ApiCropAdviceRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crop-doctor'
    | '/disease-scanner'
    | '/profile'
    | '/api/crop-advice'
    | '/api/translate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crop-doctor'
    | '/disease-scanner'
    | '/profile'
    | '/api/crop-advice'
    | '/api/translate'
  id:
    | '__root__'
    | '/'
    | '/crop-doctor'
    | '/disease-scanner'
    | '/profile'
    | '/api/crop-advice'
    | '/api/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropDoctorRoute: typeof CropDoctorRoute
  DiseaseScannerRoute: typeof DiseaseScannerRoute
  ProfileRoute: typeof ProfileRoute
  ApiCropAdviceRoute: typeof ApiCropAdviceRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-doctor': {
      id: '/crop-doctor'
      path: '/crop-doctor'
      fullPath: '/crop-doctor'
      preLoaderRoute: typeof CropDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-scanner': {
      id: '/disease-scanner'
      path: '/disease-scanner'
      fullPath: '/disease-scanner'
      preLoaderRoute: typeof DiseaseScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crop-advice': {
      id: '/api/crop-advice'
      path: '/api/crop-advice'
      fullPath: '/api/crop-advice'
      preLoaderRoute: typeof ApiCropAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropDoctorRoute: CropDoctorRoute,
  DiseaseScannerRoute: DiseaseScannerRoute,
  ProfileRoute: ProfileRoute,
  ApiCropAdviceRoute: ApiCropAdviceRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
